version: '3.9'

services:
  web:
    build: .
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - code-volume:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: doguser
      POSTGRES_PASSWORD: dogpass
      POSTGRES_DB: dogdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  code-volume:
  db-data: